bitacora_app/bitacora_app/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    
    #url de autenticación de django
    # path('', include('django.contrib.auth.urls')), 
    path('',include('reporte_operaciones.urls')),
    #aplicación principal

]

bitacora_app/reporte_operaciones/urls.py
from django.urls import path,include
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path("",views.login_usuario, name = "login"),
    path('logout/', views.logout_view, name='logout'),
    #URLs departamento operaciones
    path('home_operaciones/',views.home_operaciones, name='home_operaciones'),    
    path("agregar_conductor/",views.agregar_conductor, name="agregar_conductor"),
    path('agregar_vehiculo/',views.agregar_vehiculo, name="agregar_vehiculo"),
    path("crear_reporte/",views.crear_reporte,name="crear_reporte"),
    path("crear_reporte/<int:reporte_id>/",views.reporte_informacion,name="reporte_informacion"),
    
    #URLs departamento taller
    path("home_taller/", views.reportes_reparaciones, name ="reportes_reparaciones"),   
    path("home_taller/modificar_reporte/<int:id_reparacion>/",views.modificar_reporte, name = 'modificar_reporte') ,
    #URLs mecanicos
    path("home_mecanico/", views.home_mecanico, name ="home_mecanico"),
    path('crear_reporte_mecanico/<int:id_reparacion>/',views.crear_reporte_mecanico,name='crear_reporte_mecanico'),
    path('cargar-reparaciones/', views.cargar_reparaciones, name='cargar_reparaciones'),
    #Supervisores 
    path('home_supervisor/', views.home_supervisor, name='home_supervisor'),
    # path('dashboard/', views.dashboard, name='dashboard'),
    #Calculo de tiempo Mecanico
    path('iniciar_trabajo/<int:id_reporte_mecanico>/', views.iniciar_trabajo, name='iniciar_trabajo'),
    path('detener_trabajo/<int:id_reporte_mecanico>/', views.detener_trabajo, name='detener_trabajo'),

    #Dashboar
    path('home_dashboard/',views.dashboard_view_uno, name = 'dashboard_view_uno'),
    path('home_dashboard_dos/',views.dashboard_view_dos, name = 'dashboard_view_dos')
]

bitacora_app/reporte_operaciones/models.py
from django.contrib.auth.models import AbstractUser


from django.db import models
from datetime import date 
from enum import Enum
from django.utils import timezone
from datetime import datetime, timedelta
class Departamento(Enum):
    OPERACIONES = 'Operaciones'
    TALLER = 'Taller'
    ALMACEN = 'Almacen'
    MECANICO = 'Mecanico'
    SUPERVISOR = 'Supervisor'
    JEFE_DEPARTAMENTO = 'Jefe Departamento'
    @classmethod
    def choices(cls):
        return [(key.name, key.value) for key in cls]    

class Especialidad(Enum):
    MOTOR = 'Motor'
    FRENOS = 'Frenos'
    SUSPENSION = 'Suspensión'
    ELECTRICO = 'Eléctrico'
    RESCATISTA = 'Rescatista'
    MUELLERO = 'Muellero'
    TEC_PINTOR = 'Técnico Pintor'
    PINTOR = 'Pintor'
    AYU_ELECTRICO = 'Ayudante Eléctrico'
    CARROCERO = 'Carrocero'
    AYU_CARROCERO = 'Ayudante Carrocero'
    SOLDADOR = 'Soldador'
    LAVADO_MOTOR = 'Lavadores de Motores'
    TEC_MEC_AUTOMOTRIZ = 'Técnico Mecánico Automotriz'
    TEC_ELEC_AUTOMOTRIZ = 'Técnico Electrico Automotriz'

    @classmethod
    def choices(cls):
        return [(key.name, key.value) for key in cls]
    
class UsuarioAutocar(AbstractUser):
    departamento = models.CharField(
        max_length=20,
        choices=Departamento.choices()
    )
    especialidad = models.CharField(
        max_length=20,
        choices=Especialidad.choices(),
        blank=True,
        null=True
    )
    def __str__(self):
        return f"{self.first_name} {self.last_name} "   
    def es_mecanico(self):
        return self.departamento == Departamento.MECANICO.name    


class ZonaVehiculos(Enum):
    NORTE = 'Norte'
    SUR = 'Sur'
    HOTELES = 'Hoteles'
    @classmethod
    def choices(cls):
        return [(key.name, key.value) for key in cls]        



class Conductor(models.Model):
    id_conductor = models.AutoField(primary_key=True)
    nombre_conductor = models.CharField(max_length=20)
    apellido_conductor = models.CharField(max_length=20)
    def __str__(self):
        return f"{self.nombre_conductor} {self.apellido_conductor} "  


class TipoIngreso(Enum):
    CORRECTIVO = 'Correctivo'
    RESCATE = 'Rescate'
    PREVENTIVO = 'Preventivo'
    ACCIDENTE = 'Accidente'
    @classmethod
    def choices(cls):
        return [(key.value, key.value) for key in cls]

class EstatusReporte(Enum):
    ACTIVO = 'Activo'
    SIN_ASIGNAR = 'Sin Asignar'
    TERMINADO = 'Terminado'
    SUSPENDIDO = 'Suspendido'
    
    
    @classmethod
    def choices(cls):
        return [(key.value, key.value) for key in cls]        
class Vehiculos(models.Model):
    id_vehiculo = models.AutoField(primary_key=True)  # Corrigiendo el error con primary_key
    numero_unidad = models.CharField(max_length=30)  # Agregar max_length
    modelo_unidad = models.CharField(max_length=30)
    año_unidad = models.CharField(max_length=30)
    zona_unidad = models.CharField(
        max_length=20,
        choices=ZonaVehiculos.choices()
    )
    kilometraje = models.IntegerField()
    def __str__(self):
        return f"{self.numero_unidad} {self.modelo_unidad}"  

class ReporteEntrada(models.Model):
    #Llave primaria
    id_reporte = models.AutoField(primary_key=True)
    

    #Llaves Foraneas
    conductor = models.ForeignKey('Conductor', on_delete=models.DO_NOTHING)
    reporte_usuario = models.ForeignKey('UsuarioAutocar',on_delete=models.DO_NOTHING)
    
    #Campos
    fecha_entrada = models.DateField(auto_now_add=True)
    fecha_terminado = models.DateField(null=True, blank=True, default=None)
    unidad = models.ForeignKey('Vehiculos', on_delete=models.DO_NOTHING)
    descripción_incidente = models.TextField(max_length=255)
    kilometraje_nuevo = models.IntegerField()

    def __str__(self):
        return str(self.id_reporte)

class ReporteReparacion(models.Model):
    id_reparacion = models.AutoField(primary_key=True)
    id_entrada = models.ForeignKey('ReporteEntrada',on_delete=models.CASCADE)
    id_reporte_mecanico = models.ManyToManyField('ReporteMecanico', blank=True)
    estacion = models.ForeignKey('Estacion',on_delete=models.PROTECT,default=None,null=True)
    tipo_entrada = models.CharField(
        max_length=20,
        choices=TipoIngreso.choices(),
        default='Sin Asignar'
    )
    estatus = models.CharField(
        max_length=20,
        choices=EstatusReporte.choices(),
        default = 'Pendiente',
    )

    def __str__(self):
        return str(self.id_reparacion)    

class MecanicosAsignados(models.Model):
    reporte_reparacion = models.ForeignKey('ReporteReparacion',on_delete=models.CASCADE)
    mecanico = models.ForeignKey('UsuarioAutocar',on_delete=models.CASCADE)
    #Condición para que solo sea una asignación del mecanico. No se le puede asignar dos veces al mecanico el mismo reporte
    class Meta:
        unique_together =('reporte_reparacion','mecanico')
    def __str__(self):
        return f"Reporte- {self.reporte_reparacion}, Mecanico- {self.mecanico}"

class ReporteMecanico(models.Model):
    id_mecanico = models.ForeignKey('UsuarioAutocar',on_delete=models.CASCADE)
    reporte_reparacion = models.ForeignKey('ReporteReparacion', on_delete=models.CASCADE, default=None)
    reparacion_selecionada = models.ManyToManyField('Reparacion',related_name='reparaciones',blank=True)
    estatus = models.CharField(default='Inactivo', max_length=15, blank=True,null=True)

    #tiempo de trabajo 
    fecha_inicio = models.DateField(default=None, blank=True,null=True)
    hora_inicio = models.TimeField(default=None,blank=True,null=True)    
    fecha_terminado = models.DateTimeField(default=None,blank=True,null=True)
    hora_termiando = models.TimeField(default=None,blank=True,null=True)
    tiempo_acumulado = models.DurationField(default=None,blank=True,null=True)
    def __str__(self):
        return f"{self.reporte_reparacion} {self.id}, {self.id_mecanico}"
    def iniciar_trabajo(self):
        ahora = timezone.now()
        self.fecha_inicio = ahora.date()
        self.hora_inicio = ahora.time()  
        self.save()
    def detener_trabajo(self):
        if self.hora_inicio:
            # Asegura que ambos objetos datetime sean "offset-aware"
            inicio = timezone.make_aware(
                timezone.datetime.combine(self.fecha_inicio, self.hora_inicio),
                timezone.get_current_timezone()
            )
            fin = timezone.now()  # Este ya es "offset-aware"
            
            # Inicializa tiempo_acumulado si es None
            if self.tiempo_acumulado is None:
                self.tiempo_acumulado = timedelta(0)
            
            # Calcula el tiempo transcurrido y lo acumula
            self.tiempo_acumulado += (fin - inicio)
            
            # Guarda los tiempos de terminación
            self.fecha_terminado = fin.date()
            self.hora_terminado = fin.time()
            
            # Limpia los campos de inicio para la próxima sesión de trabajo
            self.fecha_inicio = None
            self.hora_inicio = None
            self.save()    
class TipoReparacion(models.Model):
    tipo_reparacion = models.CharField(max_length=15)
    def __str__(self):
        return self.tipo_reparacion

class Reparacion(models.Model):
    tipo_reparacion = models.ForeignKey('TipoReparacion',on_delete=models.CASCADE)
    reparacion = models.CharField(max_length=30) 
    def __str__(self):
        return self.reparacion

DISPONIBILIDAD = [
    ('SI', 'Disponible'),
    ('NO', 'Ocupado')
]
class Estacion(models.Model):
    estado = models.CharField(max_length=15,choices=DISPONIBILIDAD, default='SI')
    num_estacion = models.IntegerField(blank=True,default=None)
    def __str__(self):
        return f"Estacion: {self.num_estacion} Estado : {self.get_estado_display()}"

class CantidadBuses(models.Model):
    zona_unidad = models.CharField(
        max_length=20,
        choices=ZonaVehiculos.choices()
    )
    cantidad = models.IntegerField(blank=True,default=0)
    def __str__(self):
        return f"{self.zona_unidad} : {self.cantidad}"

class PiezasAlmacen(models.Model):
    id_pieza = models.AutoField(primary_key=True)
    nombre_pieza = models.CharField(max_length=100)
    sku = models.CharField(max_length=100)

class PiezasUsadas(models.Model):
    reporte_reparacion = models.ForeignKey('ReporteReparacion',on_delete=models.CASCADE)
    pieza = models.ForeignKey('PiezasAlmacen',on_delete=models.CASCADE)
    cantidad = models.IntegerField()

bitacora_app/reporte_operaciones/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
#Modelos
from .models import ReporteEntrada, UsuarioAutocar, Conductor, Vehiculos, MecanicosAsignados, ReporteReparacion,Departamento,Especialidad,ReporteReparacion,ReporteMecanico,TipoReparacion,Reparacion,Estacion,ZonaVehiculos
from django.contrib.auth.admin import UserAdmin

#Forms para usuario operaciones
class CrearReporteNuevo(forms.ModelForm):
    class Meta:
        model = ReporteEntrada
        fields =['id_reporte', 'unidad','conductor', 'descripción_incidente' , 'kilometraje_nuevo']

        widgets = {
            'unidad' : forms.Select(attrs={'class':'form-control'}),
            'conductor' : forms.Select(attrs={'class':'form-control'}),
            'descripción_incidente' : forms.Textarea(attrs={'class':'form-control'}),
            'kilometraje_nuevo' : forms.TextInput(attrs={'class':'form-control'}),
        }

class AgregarConductor(forms.ModelForm):
    class Meta:
        model = Conductor
        fields = ['nombre_conductor','apellido_conductor']

        widgets = {
            'nombre_conductor' : forms.TextInput(attrs={'class':'form-control'}),
            'apellido_conductor' : forms.TextInput(attrs={'class':'form-control'})
        }

class AgregarVehiculo(forms.ModelForm):
    class Meta:
        model = Vehiculos
        fields= ['numero_unidad','modelo_unidad','año_unidad','zona_unidad','kilometraje']

        widgets = {
            'numero_unidad' : forms.TextInput(attrs={'class':'form-control'}),
            'modelo_unidad' : forms.TextInput(attrs={'class':'form-control'}),
            'año_unidad' : forms.TextInput(attrs={'class':'form-control'}),
            'zona_unidad' : forms.Select(attrs={'class':'form-control'}),
            'kilometraje' : forms.TextInput(attrs={'class':'form-control'}),
        }

        
# Cambia el formulario de la pagina admin
class UsuarioAutocarCreacionForm(UserCreationForm):
    class Meta(UserCreationForm):
        model = UsuarioAutocar
        fields = ["username",
        "first_name",
        "last_name",
        "departamento",
        "especialidad",
        "password"]

class UsuarioAutocarCabioForm(UserChangeForm):
    class Meta:
        model = UsuarioAutocar
        fields= UserChangeForm.Meta.fields 
# FORMULARIO PARA MODIFICAR REPORTE_TALLER
class ModificarReporteReparacion(forms.ModelForm):
    class Meta:
        model = ReporteReparacion
        fields = ['tipo_entrada','estatus']

        widgets = {
            'tipo_entrada' : forms.Select(attrs={'class': 'form-control'}),
            'estatus' : forms.Select(attrs={'class': 'form-control'}),
        }
# ASIGNAR MECANICOS
class FiltroMecanicosForm(forms.Form):
    especialidad = forms.ChoiceField(
        choices=Especialidad.choices(),
        required=True,
        label="Especialidad",
        widget = forms.Select(attrs={'class':'form-control'})
    )

class AsignarMecanico(forms.ModelForm):
    mecanico = forms.ModelChoiceField(
        queryset=UsuarioAutocar.objects.filter(departamento=Departamento.MECANICO.name),
        widget= forms.Select(attrs={'class':'form-control'})
    )
    class Meta:
        model = MecanicosAsignados
        fields = ['mecanico']


class FiltroAsignarMecanicoForm(forms.Form):
    especialidad = forms.ChoiceField(
        choices=Especialidad.choices(),
        required=True,
        label="Especialidad",
        widget=forms.Select(attrs={'class': 'form-control', 'id': 'especialidad-select'})
    )
    mecanico = forms.ModelChoiceField(
        queryset=UsuarioAutocar.objects.none(),  # Inicialmente vacío, se llenará con AJAX
        widget=forms.Select(attrs={'class': 'form-control', 'id': 'mecanico-select'})
    )

    def __init__(self, *args, **kwargs):
        especialidad_seleccionada = kwargs.pop('especialidad_seleccionada', None)
        super().__init__(*args, **kwargs)
        if especialidad_seleccionada:
            self.fields['mecanico'].queryset = UsuarioAutocar.objects.filter(
                departamento=Departamento.MECANICO.name, especialidad=especialidad_seleccionada
            )



class ReparacionSeleccionForm(forms.ModelForm):
    tipo_reparacion = forms.ModelChoiceField (
        label='Area de Reparación',
        queryset =  TipoReparacion.objects.all(),
        widget = forms.Select(attrs={'class':'form-control'})
    )
    reparacion = forms.ModelMultipleChoiceField(
        queryset=Reparacion.objects.none(),
        widget=forms.CheckboxSelectMultiple(attrs={'class':'form-check'}),
        label="Reparacion"
    )

    class Meta:
        model = ReporteMecanico
        fields = ['reparacion_selecionada']

    def save(self, commit=True):
        instance = super().save(commit=False)
        instance.subreparacion = self.cleaned_data.get('subreparacion')
        if commit:
            instance.save()
        return instance     


class descripcion_reparacion(forms.ModelForm):
    REPARACION_CHOICES = [
        ('carroceria_imagen','Carrocería e Imagen'),
        ('cristales','Cristales'),
        ('direccion','Dirección'),  
        ('eje_delantero','Eje Delantero'),
        ('eje_trasero','Eje Trasero'),
        ('frenos','Frenos'),
        ('electrico','Electrico'),
        ('llantas','Llantas'),
        ('motor','Motor'),
        ('neumatico','Neumatico'),
        ('suspencion','Suspención'),
        ('transmision','Transmisión')
    ]
    tipo_reparacion = forms.ChoiceField(choices=REPARACION_CHOICES, label="Tipo de Reparación")
    subreparacion = forms.MultipleChoiceField(
        choices=[],  # Este campo se llenará dinámicamente
        widget=forms.CheckboxSelectMultiple,  # Usamos checkboxes para múltiples selecciones
        label="Sub-Reparación"
    )
    class Meta:
        model = ReporteMecanico
        fields = ['tipo_reparacion', 'subreparacion']

    def save(self, commit=True):
        instance = super().save(commit=False)
        instance.subreparacion = ','.join(self.cleaned_data.get('subreparacion'))
        if commit:
            instance.save()
        return instance     

class EstacionForm(forms.Form):
    estacion = forms.ModelChoiceField(
        queryset=Estacion.objects.all(),
        widget=forms.Select(attrs={'class': 'form-control'})  # Opcional: agrega una clase CSS
    )
    

class MecanicoForm(forms.Form):
    mecanico = forms.ModelChoiceField(
        queryset=UsuarioAutocar.objects.filter(departamento='MECANICO'),
        label="Mecánico",
        empty_label="Seleccione un mecánico",
    )

bitacora_app/reporte_operaciones/templates/reporte_operaciones/asignar_mecanico.html
{%extends "reporte_operaciones/base_template.html"%}
{%block title%}Asignar Mecanico {%endblock%}

{%block contenido%}
<form method="post" ">
    {% csrf_token %}
    {{form.as_p}}

    <button type="submit",name=asignar_mecanico, value="asignar_mecanico">Asignar</button>

</form>
{%endblock%}

bitacora_app/reporte_operaciones/templates/reporte_operaciones/base_template.html
<!DOCTYPE html>
<html lang="es">
{%block head%}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{%block title%} Taller Mecánico {% endblock %}</title> 

    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
{%endblock%}
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
                <a class="navbar-brand" href="#"></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                    <div class="navbar-nav">
                        {% block navbar %}
                        {% endblock %}
                    </div>
                    {% if user.is_authenticated %}
                        <!-- Alinea el enlace de "Cerrar sesión" a la derecha -->
                        <div class="navbar-nav ms-auto">
                            <a class="nav-link" href="{% url 'logout' %}">Cerrar sesión</a>
                        </div>
                    {% endif %}
                </div>
            </div>
        </nav>
    </header>


    <main>
            {%block contenido%}
            {%endblock%} 
    </main>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
<footer>
    {%block footer %}
    {%endblock%}
</footer>

</body>
</html>

bitacora_app/reporte_operaciones/templates/reporte_operaciones/crear_reporte.html
{%extends "reporte_operaciones/base_template.html"%}
{%block title%}Crear Nuevo Reporte {%endblock%}
{%block navbar %}         
<a class="nav-link active" aria-current="page" href="/home_operaciones/">Inicio</a>
<a class="nav-link" href="/crear_reporte/">Crear Reporte</a>
<a class="nav-link" href="/agregar_vehiculo/">Agregar Vehículo</a>
<a class="nav-link" href="/agregar_conductor/">Agregar Conductor</a>
<a class="nav-link">Usuario: {{usuario_logueado}}</a>
<a class="nav-link">Departamento: {{departamento_usuario}}</a>
{%endblock%}

{%block contenido%}
<div class="contain text-center">
    <h1>{{button}}</h1>
</div>
<div class="container">
    <div class="m-4 d-flex justify-content-center align-items-center">
        <div>
            <form method="post" >
                    {% csrf_token %}
                    {{form.as_p}}                
                <button class="btn btn-primary btn-lg" type="submit",name=crear_reporte, value="crear_reporte">{{button}}</button>
                <button class="btn btn-primary btn-lg" onclick="location.href = '/home_operaciones/'">Inicio </button>
            </form>
        </div>
    </div>
</div>
{%endblock%}

bitacora_app/reporte_operaciones/templates/reporte_operaciones/reporte_mecanico.html
{% extends 'reporte_operaciones/base_template.html' %}
{% block title %}Reporte Entradas Al Taller {% endblock %}
<body>
    {%block navbar %}         
    <a class="nav-link active" aria-current="page" href="/home_mecanico/">Inicio</a>
    <a class="nav-link">Usuario: {{usuario_logueado}}</a>
    <a class="nav-link">Departamento: {{departamento_usuario}}</a>
    {%endblock%}
    <h1>Reporte de Entradas al Taller Número: {{reporte.id_reparacion}}</h1>
    {% block contenido %}
    <div class="contain text-center">
        <h1>Reporte Mecánico Descripción</h1>
    </div>
    </div>
    <div class="container">
        <div class="m-4 d-flex justify-content-center align-items-center" >
            <table class ="table table-striped">
                <thead>
                    <tr style="background-color: #f2f2f2;">
                        <th>Id Reporte</th>
                        <th>Usuario</th>
                        <th>Fecha Entrada</th>
                        <th>Unidad</th>
                        <th>Zona</th>
                        <th>KM Anterior</th>
                        <th>KM Nuevo</th>
                        <th>Conductor</th>
                        <th>Descripción</th>
                        <th>Estatus</th>
                        <th>Entrada Por:</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>{{ reporte.id_entrada }}</td>
                        <td>{{ reporte.id_entrada.reporte_usuario }}</td>
                        <td>{{ reporte.id_entrada.fecha_entrada }}</td>
                        <td>{{ reporte.id_entrada.unidad }}</td>
                        <td>{{ reporte.id_entrada.unidad.zona_unidad }}</td>
                        <td>{{ reporte.id_entrada.unidad.kilometraje }}</td>
                        <td>{{ reporte.id_entrada.kilometraje_nuevo }}</td>
                        <td>{{ reporte.id_entrada.conductor }}</td>
                        <td><textarea maxlength="30">{{ reporte.id_entrada.descripcion_incidente }}</textarea></td>
                        <td>{{ reporte.estatus }}</td>
                        <td>{{ reporte.tipo_entrada }}</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col col-lg-4">        
                <form method="POST">
                    {% csrf_token %}                    
                        <div class="form-group">
                            <label for="id_tipo_reparacion">Área de Reparación:</label>
                            {{ form.tipo_reparacion }}
                        </div>
                        <!-- Aquí se cargarán las opciones de reparación dinámicamente -->
                        <div id="reparacion-container" class="form-group mt-3">
                            <label>Reparación:</label>
                            <div class="row" id="id_reparacion"></div>
                        </div>
                        <button class="btn btn-primary btn-lg" type="submit" value="crear_reporte">Guardar</button>    
                </form>
            </div>
            <div class="col mt-5">
                <h5>Reparaciones Realizadas</h5>
                {% for reporte_mecanico in reparaciones %}
                    <h6>Reporte del Mecánico: {{ reporte_mecanico.id_mecanico }}</h6>
                    <ul>
                        {% for reparacion in reporte_mecanico.reparacion_selecionada.all %}
                            <li>{{ reparacion.reparacion }}</li>
                        {% endfor %}
                    </ul>
                {% empty %}
                    <p>No se han registrado reparaciones para este reporte.</p>
                {% endfor %}
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('#id_tipo_reparacion').change(function () {
                var tipoReparacionID = $(this).val();
                $.ajax({
                    url: "{% url 'cargar_reparaciones' %}",
                    data: {
                        'tipo_reparacion': tipoReparacionID
                    },
                    success: function (data) {
                        let reparacionField = $('#id_reparacion');
                        reparacionField.empty();
                        $.each(data, function (index, reparacion) {
                            reparacionField.append(
                                $('<label class="form-check-label">').text(reparacion.nombre)
                                    .prepend($('<input type="checkbox" class="form-check-input">')
                                    .attr('value', reparacion.id).attr('name', 'reparacion'))
                            );
                        });
                    }
                });
            });
        });
    </script>
        
    {%endblock%}

</body>

bitacora_app/reporte_operaciones/templates/reporte_operaciones/reportes_reparaciones.html
{%extends 'reporte_operaciones/base_template.html'%}
{%block title%}Reporte Entradas Al Taller {%endblock%}
<body>
    <h1>Lista de Reporte de Entradas al Taller</h1>
    {%block contenido%}
    {% for reporte in lista_reporte %}
    <div id="incidente_div">
        <ul>
                <li>ID REPORTE : {{ reporte.id_entrada.id_reporte }}</li>
                <li>USUARIO: {{ reporte.id_entrada.reporte_usuario }}</li>
                <li>FECHA: {{ reporte.id_entrada.fecha_entrada }}</li>
                <li>UNIDAD: {{ reporte.id_entrada.unidad }} KILOMETRAJE :{{reporte.id_entrada.unidad.kilometraje}} ZONA :{{reporte.id_entrada.unidad.zona_unidad}} </li>
                <li>NUEVO KM : {{reporte.id_entrada.kilometraje_nuevo}} </li>
                <li>CONDUCTOR: {{ reporte.id_entrada.conductor }}</li>
                <li>DESCRIPCION: {{ reporte.id_entrada.descripcion_incidente }} </li>
                <li>STATUS: {{reporte.estatus}}</li>
                <li>ENTRADA POR:{{reporte.tipo_entrada}} </li>
        </ul>
        <button onclick="location.href='{% url 'modificar_reporte' reporte.id_reparacion %}'">Modificar Reporte</button>
    </div>
    {% empty %}
    <li>No hay objetos disponibles.</li>
    {% endfor %}
    {%endblock%}

</body>
</html>